### PR TITLE
Support IAM creds

### PR DESCRIPTION
**Pull request by harshavardhana**

### CODE REVIEW

**Comment by jaym** [comment]
It looks like the static credentials always win. Removing that, minio comes up with random credentials. I tried setting constant credentials in the config.json to see if minio would require requests to use those and it does not work. So the only downside (assuming the static credentials are removed from the chain) is that you have to parse the minio output to get the credentials to talk to minio with.

**Comment by harshavardhana** [comment]
> It looks like the static credentials always win. Removing that, minio comes up with random credentials. I tried setting constant credentials in the config.json to see if minio would require requests to use those and it does not work. So the only downside (assuming the static credentials are removed from the chain) is that you have to parse the minio output to get the credentials to talk to minio with.

Gateway will never read from `config.json` i don't know where you see that. This also only for S3 gateway.

**Comment by jaym** [comment]
Thought it might work, so I tried it as it seemed like a way to set the credentials that minio would accept instead of generating random ones.

Regardless of that, the static credentials need to be removed from the chain.
The error you get with that bit of code in there is:
```
-> minio gateway s3
ERROR Unable to initialize gateway backend. The AWS Access Key Id you provided does not exist in our records.
```

**Comment by harshavardhana** [comment]
Updating PR with some proper fix.

**Comment by harshavardhana** [comment]
check again this fix should be fine..

**Pull request merged**
